let all_product = [
  {
    id: 1,
    name: "Lip Reneqing Hydrator",
    category: "",
    image: "",
    price: 14.0,
  },
  {
    id: 2,
    name: "Skincare Kit (Donation event)",
    category: "",
    image: "",
    price: 35.0,
  },
  {
    id: 3,
    name: "Corthe Dermo Essential Rich M Cream",
    category: "",
    image: "",
    price: 40.0,
  },
  {
    id: 4,
    name: "HydraRemedy Gel Serum ",
    category: "",
    image: "",
    price: 45.0,
  },
  {
    id: 5,
    name: "TIZO Mineral Sun Defense SPF50 Tinted",
    category: "",
    image: "",
    price: 45.0,
  },
  {
    id: 6,
    name: "KRX All Day Glow Aqua Glow",
    category: "",
    image: "",
    price: 39.0,
  },
  {
    id: 7,
    name: "KRX Pre Cleansing Oil",
    category: "",
    image: "",
    price: 40.0,
  },
  {
    id: 8,
    name: "TiZo 3 Tinted Primer/sunscreen",
    category: "",
    image: "",
    price: 45.0,
  },
  {
    id: 9,
    name: "Tizo Ultra Zinc Tinted Body and Face SPF 40",
    category: "",
    image: "",
    price: 45.0,
  },
  {
    id: 10,
    name: "TIZO 2 Facial Mineral Primer/Sunscreen (non-tinted)",
    category: "",
    image: "",
    price: 45.0,
  },
  {
    id: 11,
    name: "Tizo Non Tinted Ultra Zinc Body and Face Sunscreen SPF 40",
    category: "",
    image: "",
    price: 45.0,
  },
  {
    id: 12,
    name: "Barrier Balance Creamy Cleanser",
    category: "",
    image: "",
    price: 35.0,
  },
  {
    id: 13,
    name: "Mandelic Face and Body Scrub",
    category: "",
    image: "",
    price: 37.0,
  },
  {
    id: 14,
    name: "Clear Skin Balance Supplements",
    category: "",
    image: "",
    price: 42.0,
  },
  {
    id: 15,
    name: "Clear Skin Restore Supplements",
    category: "",
    image: "",
    price: 34.0,
  },
  {
    id: 16,
    name: "Sulfur Spot Treatment",
    category: "",
    image: "",
    price: 33.0,
  },
  {
    id: 17,
    name: "Antioxidant Peptide Serum",
    category: "",
    image: "",
    price: 54.0,
  },
  {
    id: 18,
    name: "Acne Face & Body Wash",
    category: "",
    image: "",
    price: 35.0,
  },
  {
    id: 19,
    name: "Ultra Gentle Cleanser",
    category: "",
    image: "",
    price: 31.0,
  },
  { id: 20, name: "Mandelic Face Wash", category: "", image: "", price: 35.0 },
  { id: 21, name: "Sal-C Toner", category: "", image: "", price: 29.0 },
  {
    id: 22,
    name: "Moisture Balance Toner",
    category: "",
    image: "",
    price: 32.0,
  },
  { id: 23, name: "Hydrabalance", category: "", image: "", price: 29.0 },
  { id: 24, name: "Cran-Peptide Cream", category: "", image: "", price: 29.0 },
  { id: 25, name: "Clearderma", category: "", image: "", price: 29.0 },
  { id: 26, name: "Hydracalm Mask", category: "", image: "", price: 40.0 },
  {
    id: 27,
    name: "Mineral Matte SPF 28",
    category: "",
    image: "",
    price: 34.0,
  },
  { id: 28, name: "Gift Cards", category: "", image: "", price: 50.0 - 200.0 },
];
